name: eosc454-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - discretize
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyter
  - ipykernel
  - scikit-learn
  - pip
  - pip:
      - simpeg
